import './globals.css'
import type { Metadata } from 'next'
import { auth } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";
import { Inter } from 'next/font/google'
import { ClerkProvider} from '@clerk/nextjs'
import { Toastprovider } from '@/components/providers/toaster-provider'
import { ConfettiProvider } from '@/components/providers/confetti-provider';
import { db } from '@/lib/db'
import { getCourses } from "@/actions/get-courses";
import { CoursesList } from "@/components/courses-list";



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default   function  RootLayout({
  children,
}: {
  
  children: React.ReactNode

}) {

  

  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <ConfettiProvider />
        <Toastprovider />
        {children}
        </body>
    </html>
    </ClerkProvider>

    
  )
}





// import { getCourses } from "@/actions/get-courses";

// // import { Categories } from "./_components/categories";

// interface SearchPageProps {
//   searchParams?: {
//     title?: string;
//     categoryId?: string;
//   };
// }

// const SearchPage = async ({ searchParams =  {} }: SearchPageProps) => {
//   const { userId } = await auth();
//   const searchp = await searchParams;

//   if (!userId) {
//     return redirect("/");
//   }

//   const categories = await db.category.findMany({
//     orderBy: {
//       name: "asc",
//     },
//   });

//   const courses = await getCourses({
//     userId,
//     ...searchp,
//   });

//   return (
//     <>
//       <div className="px-6 pt-6 md:hidden md:mb-0 block">
//         <SearchInput />
//       </div>
      // <div className="p-6 space-y-4">
      //   {/* <Categories items={categories} /> */}
      //   <CoursesList items={courses} />
      // </div>
//     </>
//   );
// };

// export default SearchPage;
